repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: name-tests-test
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      args: [--max-line-length=79]
#       stages: [manual]
- repo: https://github.com/psf/black.git
  rev: 20.8b1
  hooks:
    - id: black
      exclude: |
        (?x)(
            migrations/|
            ^\.git/|
            ^cache/|
            ^\.cache/|
            ^\.venv/|
            ^\.local
        )
      language_version: python3.7
      stages: [commit]
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit.git
  rev: v1.0.4
  hooks:
  - id: python-bandit-vulnerability-check
    args: [--verbose, --recursive, -x, tests]
    files: .py$
